version: '3.4'
#docker-compose -f docker-compose.yml up -d

services:

  mongo:
    #mongodb://localhost:27017/
    container_name: snipefish_db
    image: mongo
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
    ports:
        - 27017:27017

  mongo-express:
    #http://localhost:8090/
    container_name: snipefish_db_admin
    image: mongo-express
    restart: always
    ports:
        - 8090:8081
    environment:
        ME_CONFIG_MONGODB_SERVER: snipefish_db
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
        - mongo

  snipefish.webclient:
    #http://localhost:8091/
    container_name: snipefish_webclient
    #image: ${DOCKER_REGISTRY-}snipefishwebclient
    image: ghcr.io/chinthakadarshana1/snipefish_webclient
    restart: always
    ports:
        - 8091:80
    build:
        context: .
        dockerfile: Sniperfish.WebClient/Dockerfile
    depends_on:
        - mongo

  snipefish.webapi:
    #http://localhost:8092/swagger/index.html
    container_name: snipefish_webapi
    #image: ${DOCKER_REGISTRY-}snipefishwebapi
    image: ghcr.io/chinthakadarshana1/snipefish_webapi
    restart: always
    ports:
        - 8092:80
    build:
        context: .
        dockerfile: Sniperfish.WebApi/Dockerfile
    depends_on:
        - mongo 
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        #MongoConnections
        - MongoConfigurations__SnipefishDbConfiguration__ConnectionString=mongodb://localhost:27017/
      


